# Site settings
title: Rafael Henrique TibÃ£es
email: hi@fael.nl
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision, Machine Learning & High Performance: C++ and JuliaLang.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fael.nl" # the base hostname & protocol for your site
twitter_username: rafaeltibaes
github_username:  tibaes
permalink: /:categories/:title/

# Build settings
markdown: kramdown
