# Site settings
title: fael's bio
description: Hi, my name is Rafael Henrique Tibães. My expertise is about computer vision solutions. Hope you find valuable information here, and feel free to contact me.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rafael Henrique Tibães
user_description: Computer Vision Specialist with experience in data science, machine learning, insurance and biometrics. Holding a master’s degree in Computer Science from Federal University of Bahia (UFBA) and a bachelor’s degree in Computer Science from Federal University of Parana (UFPR).
user_title: Computer Vision Engineer
email: hi@fael.nl
twitter_username: rafaeltibaes
github_username:  tibaes

# Google-analytics
google-analytics:
  id: "UA-60502775-1"

exclude: ['package.json', 'src' , 'node_modules']
